# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'firebaseDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for firebaseDemo
  pod 'Firebase/Core'
  pod 'Firebase/Database', '~>4.0.3' 

end
